# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0b5f78c04cb4deb4cdae9f2b59f565dfad2eed055e15357cfb8a88b4f9dced7d5716818383b8570bd6bdfb4172e5a07954e92fe3e0959ff02873cf439c1778

test:
  secret_key_base: 48e72d6fe8d913a2bc7729545505074b636466a3bf006cb73b26bafa5471c4847478ec902c5715a62c5b4402e794779d68fd9aa3848338bdf3f2ad9a81851218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
